### PR TITLE
add Dockerfile, static make target

### PR DESCRIPTION
**Pull request by Eriner**
Very similar to: https://github.com/lukechampine/walrus/pull/19

### CODE REVIEW

**Comment by lukechampine** [comment]
ok, for `walrus` I didn't think about it too deeply, but I'm not sure I want Dockerfiles in *all* of my projects.
Can you briefly explain:

- What value these Dockerfiles provide
- Why they need to be checked into the repo itself instead of living elsewhere?

Thanks.

**Comment by Eriner** [comment]
Sure, if I want to run all of these binaries in one go (as in, run a `muse` server, `walrus` server, and interact with it using `user`), that isn't very easy to do right now. I have to build those binaries on my local machine, keep them up-to-date, and either build or take them with me to another machine.

These are very minimal Dockerfiles (which create Docker containers, a la `$ docker build . -t 'lukechampine/walrus:latest'` && docker run -it lukechampine/walrus:latest`) that encapsulate the underlying binaries. This ensures a clean and minimal execution environment.

Ultimately, that will let me create Kubernetes manifests (or a`docker-compose.yml` file) that, when started, runs the `muse`, `walrus`, `shard`, etc. services.

I'm working on creating it anyway for myself, but I'm happy to PR Github Actions CI files for building the containers automatically. You can elect to publish them to Dockerhub or elsewhere. One of my personal mid-term goals is to create a Docker registry (a place where these docker images are pushed to be consumed and built-upon by others) using Sia as the data backend. This is easier with S3 :)

**Comment by Eriner** [comment]
Realized I didn't answer this one:

> Why they need to be checked into the repo itself instead of living elsewhere?

Ideally the file exists within the repository. This means one can clone the repo and reproduce the container. If you notice in the Dockerfile, the build itself copies the files in the current directory (aka, the repo contents) into the container to perform the build: https://github.com/lukechampine/muse/pull/16/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R3

**Comment by lukechampine** [comment]
I think I just kinda take offense to the model where *my stuff* needs to change to be compatible with some other program that I don't use and can't provide any support for. Reminds me of "snaps" -- back before AppImage became ubiquitous, there was a competing technology called Snap, and they had an evangelist who went around opening PRs on every single repo he could find, adding a "Snapfile" (or something, don't remember) that made your app compatible with their packaging system. Really left a bad taste in my mouth. I get that Docker has a bit more staying power, but I still don't like the principle. ¯\\\_(ツ)\_/¯

The Docker image for `siad` is maintained by a third party: https://github.com/siacentral/sia-docker
I think I'd prefer that arrangement, if possible. Would you need to create a separate repo for every utility, or is it possible to host multiple Dockerfiles in one repo?

**Comment by Eriner** [comment]
I can appreciate that perspective: I feel the same way about `Makefiles` for the most part.

That being the said, unlike Snaps, deb pkgs, rpms, et. al., the `Dockerfile` as it exists in this (and other PRs) is the only thing that needs to be merged here -- there is no additional process requirement. The contents of that file are basically a glorified bash script, and it is _extremely_ minimal. Unless there are dramatic code changes, there should be nothing for you to support, as it should just work dot jpeg. It shouldn't require any code changes, or even project structural changes. And if there are issues, I am happy to support.

The nice thing about a `Dockerfile` existing in a project root is _even if the project owner doesn't provide an official image_ (as in, push an image to DockerHub or GitHub Container Registry), it is easy clone the repo and build it yourself.

If it is really that much of a burden and imposition, I will maintain the containers on my own. I just think it's nice to provide official images so that everyone doesn't have to go looking for containers in other repos or from non-Sia "internet strangers".

>  Would you need to create a separate repo for every utility, or is it possible to host multiple Dockerfiles in one repo?

It is possible to put the `Dockerfile`s anywhere, but again having them alongside the code-to-be-built is much more convenient. It also reduces complexity for both the user building the image and for the code in the `Dockerfile` itself.

**Comment by lukechampine** [comment]
Ok. I like you, so I'll allow it. But if you disappear and I end up on the hook to maintain this stuff myself, I will call the Internet Police and have you sent straight to Cyberjail. Deal?

**Comment by Eriner** [comment]
Ha, deal. :-)

**Pull request merged**
